### ISSUE TITLE
nodejs8.10 is no longer supported

### ISSUE THREAD

**Issue by gebailey** [webscale-oy/aws-cloudfront-basic-auth#3]
Creating the CloudFormation stack using `basic-auth-edge-lambda.yaml` gives the following error:
```
The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException;
```

**Comment by hmeltaus** [comment]
Hello @gebailey would you like to make a pull request to fix this? It's a small change.

**Comment by gebailey** [comment]
Sure: https://github.com/webscale-oy/aws-cloudfront-basic-auth/pull/4

The other change in there doesn't appear to have any ill effect, and it makes looking at (and editing) the code in the lambda console much easier.

**Comment by hmeltaus** [comment]
Thanks!
